/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ログイン */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description ログイン情報 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_Watari995_musclead_internal_auth_dto.LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_auth_dto.AccessTokenResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ログアウト */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_auth_dto.AccessTokenResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 認証情報のリフレッシュ */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_auth_dto.AccessTokenResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** エクササイズ一覧 */
        get: {
            parameters: {
                query?: {
                    /** @description 1ページの件数 (default: 20, max: 100) */
                    limit?: number;
                    /** @description 開始位置 (default: 0) */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_training_dto.ListExercisesResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /** エクササイズ作成 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description エクササイズ作成 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_Watari995_musclead_internal_training_dto.UpsertExerciseRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_training_dto.UpsertExerciseResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** エクササイズ取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 対象 ExerciseID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_training_dto.ExerciseDTO"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
            };
        };
        /** エクササイズ更新 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 対象 ExerciseID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description エクササイズ更新 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_Watari995_musclead_internal_training_dto.UpsertExerciseRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_training_dto.UpsertExerciseResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /** エクササイズ削除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 対象 ExerciseID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
                /** @description training_exercises から参照されている時 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ヘルスチェック */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 食事一覧 */
        get: {
            parameters: {
                query?: {
                    /** @description 1ページの件数 (default: 20, max: 100) */
                    limit?: number;
                    /** @description 開始位置 (default: 0) */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_meal_dto.ListMealsResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /** 食事記録 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 食事記録 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_Watari995_musclead_internal_meal_dto.RecordMealRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_meal_dto.RecordMealResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 食事取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 対象 MealID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_meal_dto.MealDTO"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
            };
        };
        /** 食事更新 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 対象 MealID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description 更新内容 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_Watari995_musclead_internal_meal_dto.UpdateMealRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_meal_dto.UpdateMealResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /** 食事削除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 対象 MealID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trainings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** トレーニング一覧 */
        get: {
            parameters: {
                query?: {
                    /** @description 1ページの件数 (default: 20, max: 100) */
                    limit?: number;
                    /** @description 開始位置 (default: 0) */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_training_dto.ListTrainingsResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /** トレーニング記録 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description トレーニング記録 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_Watari995_musclead_internal_training_dto.RecordTrainingRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_training_dto.RecordTrainingResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trainings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** トレーニング取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 対象 TrainingID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_training_dto.TrainingDTO"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
            };
        };
        /** トレーニング記録更新 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 対象 TrainingID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description 更新用トレーニング記録 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_Watari995_musclead_internal_training_dto.UpdateTrainingRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_training_dto.UpdateTrainingResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /** トレーニング削除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 対象 TrainingID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ユーザー登録
         * @description 新規ユーザーを作成する(認証不要)
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description ユーザー登録情報 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_Watari995_musclead_internal_user_dto.RegisterRequest"];
                };
            };
            responses: {
                /** @description ユーザー登録成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_user_dto.RegisterResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ユーザー情報取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_user_dto.UserDTO"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ユーザー取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 対象 UserID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_user_dto.UserDTO"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** ユーザー削除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 対象 UserID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "github_com_Watari995_musclead_internal_auth_dto.AccessTokenResponse": {
            access_token?: string;
            access_token_expires_at?: string;
        };
        "github_com_Watari995_musclead_internal_auth_dto.LoginRequest": {
            email?: string;
            password?: string;
        };
        "github_com_Watari995_musclead_internal_meal_dto.ListMealsResponse": {
            meals?: components["schemas"]["github_com_Watari995_musclead_internal_meal_dto.MealDTO"][];
            pagination?: components["schemas"]["github_com_Watari995_musclead_internal_shared_dto.PaginationDTO"];
        };
        "github_com_Watari995_musclead_internal_meal_dto.MealDTO": {
            calories?: number;
            carbohydrate_g?: string;
            created_at?: string;
            eaten_at?: string;
            fat_g?: string;
            id?: string;
            meal_type?: string;
            memo?: string;
            photos?: components["schemas"]["github_com_Watari995_musclead_internal_meal_dto.PhotoDTO"][];
            protein_g?: string;
            updated_at?: string;
            user_id?: string;
        };
        "github_com_Watari995_musclead_internal_meal_dto.MealPhotoInput": {
            display_order?: number;
            image_path?: string;
        };
        "github_com_Watari995_musclead_internal_meal_dto.PhotoDTO": {
            display_order?: number;
            image_url?: string;
        };
        "github_com_Watari995_musclead_internal_meal_dto.RecordMealRequest": {
            calories?: number;
            carbohydrate_g?: number;
            eaten_at?: string;
            fat_g?: number;
            meal_type?: string;
            memo?: string;
            photos?: components["schemas"]["github_com_Watari995_musclead_internal_meal_dto.MealPhotoInput"][];
            protein_g?: number;
        };
        "github_com_Watari995_musclead_internal_meal_dto.RecordMealResponse": {
            meal_id?: string;
        };
        "github_com_Watari995_musclead_internal_meal_dto.UpdateMealRequest": {
            calories?: number;
            carbohydrate_g?: number;
            eaten_at?: string;
            fat_g?: number;
            meal_type?: string;
            memo?: string;
            photos?: components["schemas"]["github_com_Watari995_musclead_internal_meal_dto.MealPhotoInput"][];
            protein_g?: number;
        };
        "github_com_Watari995_musclead_internal_meal_dto.UpdateMealResponse": {
            meal_id?: string;
        };
        "github_com_Watari995_musclead_internal_shared_dto.PaginationDTO": {
            current_page?: number;
            items_per_page?: number;
            total_items?: number;
            total_pages?: number;
        };
        "github_com_Watari995_musclead_internal_shared_httpx.ErrorDetail": {
            code?: string;
            data?: {
                [key: string]: unknown;
            };
            message?: string;
        };
        "github_com_Watari995_musclead_internal_shared_httpx.ErrorResponse": {
            error?: components["schemas"]["github_com_Watari995_musclead_internal_shared_httpx.ErrorDetail"];
        };
        "github_com_Watari995_musclead_internal_training_dto.ExerciseDTO": {
            created_at?: string;
            id?: string;
            name?: string;
            updated_at?: string;
            user_id?: string;
        };
        "github_com_Watari995_musclead_internal_training_dto.ListExercisesResponse": {
            exercises?: components["schemas"]["github_com_Watari995_musclead_internal_training_dto.ExerciseDTO"][];
            pagination?: components["schemas"]["github_com_Watari995_musclead_internal_shared_dto.PaginationDTO"];
        };
        "github_com_Watari995_musclead_internal_training_dto.ListTrainingsResponse": {
            pagination?: components["schemas"]["github_com_Watari995_musclead_internal_shared_dto.PaginationDTO"];
            trainings?: components["schemas"]["github_com_Watari995_musclead_internal_training_dto.TrainingDTO"][];
        };
        "github_com_Watari995_musclead_internal_training_dto.RecordTrainingExerciseRequest": {
            display_order?: number;
            exercise_id?: string;
            memo?: string;
            rest_seconds?: number;
            sets?: components["schemas"]["github_com_Watari995_musclead_internal_training_dto.RecordTrainingSetRequest"][];
        };
        "github_com_Watari995_musclead_internal_training_dto.RecordTrainingRequest": {
            ended_at?: string;
            exercises?: components["schemas"]["github_com_Watari995_musclead_internal_training_dto.RecordTrainingExerciseRequest"][];
            memo?: string;
            started_at?: string;
        };
        "github_com_Watari995_musclead_internal_training_dto.RecordTrainingResponse": {
            training_id?: string;
        };
        "github_com_Watari995_musclead_internal_training_dto.RecordTrainingSetRequest": {
            memo?: string;
            reps?: number;
            rest_seconds?: number;
            set_number?: number;
            weight_kg?: string;
        };
        "github_com_Watari995_musclead_internal_training_dto.TrainingDTO": {
            created_at?: string;
            ended_at?: string;
            exercises?: components["schemas"]["github_com_Watari995_musclead_internal_training_dto.TrainingExerciseDTO"][];
            id?: string;
            memo?: string;
            started_at?: string;
            updated_at?: string;
            user_id?: string;
        };
        "github_com_Watari995_musclead_internal_training_dto.TrainingExerciseDTO": {
            display_order?: number;
            exercise_id?: string;
            id?: string;
            memo?: string;
            rest_seconds?: number;
            sets?: components["schemas"]["github_com_Watari995_musclead_internal_training_dto.TrainingSetDTO"][];
        };
        "github_com_Watari995_musclead_internal_training_dto.TrainingSetDTO": {
            id?: string;
            memo?: string;
            reps?: number;
            rest_seconds?: number;
            set_number?: number;
            /** @description weightは精度のためstringとして持つ */
            weight_kg?: string;
        };
        "github_com_Watari995_musclead_internal_training_dto.UpdateTrainingRequest": {
            ended_at?: string;
            exercises?: components["schemas"]["github_com_Watari995_musclead_internal_training_dto.RecordTrainingExerciseRequest"][];
            memo?: string;
            started_at?: string;
        };
        "github_com_Watari995_musclead_internal_training_dto.UpdateTrainingResponse": {
            training_id?: string;
        };
        "github_com_Watari995_musclead_internal_training_dto.UpsertExerciseRequest": {
            name?: string;
        };
        "github_com_Watari995_musclead_internal_training_dto.UpsertExerciseResponse": {
            id?: string;
        };
        "github_com_Watari995_musclead_internal_user_dto.RegisterRequest": {
            birthday?: string;
            email?: string;
            name?: string;
            password?: string;
        };
        "github_com_Watari995_musclead_internal_user_dto.RegisterResponse": {
            user_id?: string;
        };
        "github_com_Watari995_musclead_internal_user_dto.UserDTO": {
            birthday?: string;
            created_at?: string;
            email?: string;
            id?: string;
            name?: string;
            updated_at?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
