// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package userdbgen

import (
	"context"
)

type Querier interface {
	FindUserByEmail(ctx context.Context, email string) (User, error)
	FindUserByID(ctx context.Context, id []byte) (User, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) error
}

var _ Querier = (*Queries)(nil)
