// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package userdbgen

import (
	"context"
	"database/sql"
	"time"
)

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, name, email, password_hash, birthday, deleted_at, created_at, updated_at
FROM users
WHERE email = ? AND deleted_at IS NULL
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Birthday,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, name, email, password_hash, birthday, deleted_at, created_at, updated_at
FROM users
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) FindUserByID(ctx context.Context, id []byte) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Birthday,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (id, name, email, password_hash, birthday, deleted_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
name = VALUES(name),
email = VALUES(email),
password_hash = VALUES(password_hash),
birthday = VALUES(birthday),
deleted_at = VALUES(deleted_at),
updated_at = VALUES(updated_at)
`

type UpsertUserParams struct {
	ID           []byte
	Name         string
	Email        string
	PasswordHash string
	Birthday     sql.NullTime
	DeletedAt    sql.NullTime
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.ExecContext(ctx, upsertUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Birthday,
		arg.DeletedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
