// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meals.sql

package mealdbgen

import (
	"context"
	"database/sql"
	"time"
)

const countMealsByUserID = `-- name: CountMealsByUserID :one
SELECT COUNT(*) FROM meals WHERE user_id = ?
`

func (q *Queries) CountMealsByUserID(ctx context.Context, userID []byte) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMealsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMealPhoto = `-- name: CreateMealPhoto :exec
INSERT INTO meal_photos (id, meal_id, image_path, display_order, created_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateMealPhotoParams struct {
	ID           []byte
	MealID       []byte
	ImagePath    string
	DisplayOrder int32
	CreatedAt    time.Time
}

func (q *Queries) CreateMealPhoto(ctx context.Context, arg CreateMealPhotoParams) error {
	_, err := q.db.ExecContext(ctx, createMealPhoto,
		arg.ID,
		arg.MealID,
		arg.ImagePath,
		arg.DisplayOrder,
		arg.CreatedAt,
	)
	return err
}

const deleteMealByID = `-- name: DeleteMealByID :exec
DELETE FROM meals
WHERE id = ?
`

func (q *Queries) DeleteMealByID(ctx context.Context, id []byte) error {
	_, err := q.db.ExecContext(ctx, deleteMealByID, id)
	return err
}

const deleteMealPhotosByMealID = `-- name: DeleteMealPhotosByMealID :exec
DELETE FROM meal_photos
WHERE meal_id = ?
`

func (q *Queries) DeleteMealPhotosByMealID(ctx context.Context, mealID []byte) error {
	_, err := q.db.ExecContext(ctx, deleteMealPhotosByMealID, mealID)
	return err
}

const findAllMealsByUserIDWithOffsetPagination = `-- name: FindAllMealsByUserIDWithOffsetPagination :many
SELECT id, user_id, eaten_at, meal_type, calories, protein_g, fat_g, carbohydrate_g, memo, created_at, updated_at
FROM meals
WHERE user_id = ? ORDER BY eaten_at DESC LIMIT ? OFFSET ?
`

type FindAllMealsByUserIDWithOffsetPaginationParams struct {
	UserID []byte
	Limit  int32
	Offset int32
}

func (q *Queries) FindAllMealsByUserIDWithOffsetPagination(ctx context.Context, arg FindAllMealsByUserIDWithOffsetPaginationParams) ([]Meal, error) {
	rows, err := q.db.QueryContext(ctx, findAllMealsByUserIDWithOffsetPagination, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Meal{}
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EatenAt,
			&i.MealType,
			&i.Calories,
			&i.ProteinG,
			&i.FatG,
			&i.CarbohydrateG,
			&i.Memo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findMealByID = `-- name: FindMealByID :one
SELECT id, user_id, eaten_at, meal_type, calories, protein_g, fat_g, carbohydrate_g, memo, created_at, updated_at
FROM meals
WHERE id = ?
`

func (q *Queries) FindMealByID(ctx context.Context, id []byte) (Meal, error) {
	row := q.db.QueryRowContext(ctx, findMealByID, id)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EatenAt,
		&i.MealType,
		&i.Calories,
		&i.ProteinG,
		&i.FatG,
		&i.CarbohydrateG,
		&i.Memo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findMealPhotosByMealID = `-- name: FindMealPhotosByMealID :many
SELECT id, meal_id, image_path, display_order, created_at
FROM meal_photos
WHERE meal_id = ? ORDER BY display_order ASC
`

func (q *Queries) FindMealPhotosByMealID(ctx context.Context, mealID []byte) ([]MealPhoto, error) {
	rows, err := q.db.QueryContext(ctx, findMealPhotosByMealID, mealID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MealPhoto{}
	for rows.Next() {
		var i MealPhoto
		if err := rows.Scan(
			&i.ID,
			&i.MealID,
			&i.ImagePath,
			&i.DisplayOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMeal = `-- name: UpsertMeal :exec
INSERT INTO meals (id, user_id, eaten_at, meal_type, calories, protein_g, fat_g, carbohydrate_g, memo, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
eaten_at = VALUES(eaten_at),
meal_type = VALUES(meal_type),
calories = VALUES(calories),
protein_g = VALUES(protein_g),
fat_g = VALUES(fat_g),
carbohydrate_g = VALUES(carbohydrate_g),
memo = VALUES(memo),
updated_at = VALUES(updated_at)
`

type UpsertMealParams struct {
	ID            []byte
	UserID        []byte
	EatenAt       time.Time
	MealType      string
	Calories      int32
	ProteinG      sql.NullString
	FatG          sql.NullString
	CarbohydrateG sql.NullString
	Memo          sql.NullString
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) UpsertMeal(ctx context.Context, arg UpsertMealParams) error {
	_, err := q.db.ExecContext(ctx, upsertMeal,
		arg.ID,
		arg.UserID,
		arg.EatenAt,
		arg.MealType,
		arg.Calories,
		arg.ProteinG,
		arg.FatG,
		arg.CarbohydrateG,
		arg.Memo,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
