// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package mealdbgen

import (
	"database/sql"
	"time"
)

type Meal struct {
	ID            []byte
	UserID        []byte
	EatenAt       time.Time
	MealType      string
	Calories      int32
	ProteinG      sql.NullString
	FatG          sql.NullString
	CarbohydrateG sql.NullString
	Memo          sql.NullString
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type MealPhoto struct {
	ID           []byte
	MealID       []byte
	ImagePath    string
	DisplayOrder int32
	CreatedAt    time.Time
}

type User struct {
	ID           []byte
	Name         string
	Email        string
	PasswordHash string
	Birthday     sql.NullTime
	DeletedAt    sql.NullTime
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
