// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package mealdbgen

import (
	"context"
)

type Querier interface {
	CountMealsByUserID(ctx context.Context, userID []byte) (int64, error)
	CreateMealPhoto(ctx context.Context, arg CreateMealPhotoParams) error
	DeleteMealByID(ctx context.Context, id []byte) error
	DeleteMealPhotosByMealID(ctx context.Context, mealID []byte) error
	FindAllMealsByUserIDWithOffsetPagination(ctx context.Context, arg FindAllMealsByUserIDWithOffsetPaginationParams) ([]Meal, error)
	FindMealByID(ctx context.Context, id []byte) (Meal, error)
	FindMealPhotosByMealID(ctx context.Context, mealID []byte) ([]MealPhoto, error)
	FindMealPhotosByMealIDs(ctx context.Context, mealIds [][]byte) ([]MealPhoto, error)
	UpsertMeal(ctx context.Context, arg UpsertMealParams) error
}

var _ Querier = (*Queries)(nil)
