/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ログイン */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description ログイン情報 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["authdto.LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["authdto.AccessTokenResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ログアウト */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["authdto.AccessTokenResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 認証情報のリフレッシュ */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["authdto.AccessTokenResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** エクササイズ一覧 */
        get: {
            parameters: {
                query?: {
                    /** @description 1ページの件数 (default: 20, max: 100) */
                    limit?: number;
                    /** @description 開始位置 (default: 0) */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["trainingdto.ListExercisesResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /** エクササイズ作成 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description エクササイズ作成 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["trainingdto.UpsertExerciseRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["trainingdto.UpsertExerciseResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** エクササイズ取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 対象 ExerciseID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["trainingdto.ExerciseDTO"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        /** エクササイズ更新 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 対象 ExerciseID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description エクササイズ更新 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["trainingdto.UpsertExerciseRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["trainingdto.UpsertExerciseResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /** エクササイズ削除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 対象 ExerciseID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description training_exercises から参照されている時 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ヘルスチェック */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 食事一覧 */
        get: {
            parameters: {
                query?: {
                    /** @description 1ページの件数 (default: 20, max: 100) */
                    limit?: number;
                    /** @description 開始位置 (default: 0) */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["mealdto.ListMealsResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /** 食事記録 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 食事記録 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["mealdto.RecordMealRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["mealdto.RecordMealResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 食事取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 対象 MealID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["mealdto.MealDTO"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        /** 食事更新 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 対象 MealID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description 更新内容 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["mealdto.UpdateMealRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["mealdto.UpdateMealResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /** 食事削除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 対象 MealID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ルーティン一覧 */
        get: {
            parameters: {
                query?: {
                    /** @description 1ページの件数 (default: 20, max: 100) */
                    limit?: number;
                    /** @description 開始位置 (default: 0) */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["trainingdto.ListRoutinesResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /** ルーティン作成 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description ルーティン作成 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["trainingdto.UpsertRoutineRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["trainingdto.UpsertRoutineResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description 同 user 内で名前重複 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routines/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ルーティン詳細取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 対象 RoutineID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["trainingdto.RoutineDTO"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        /** ルーティン更新 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 対象 RoutineID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description ルーティン更新 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["trainingdto.UpsertRoutineRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["trainingdto.UpsertRoutineResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description 同 user 内で名前重複 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /** ルーティン削除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 対象 RoutineID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trainings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** トレーニング一覧 */
        get: {
            parameters: {
                query?: {
                    /** @description 1ページの件数 (default: 20, max: 100) */
                    limit?: number;
                    /** @description 開始位置 (default: 0) */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["trainingdto.ListTrainingsResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /** トレーニング記録 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description トレーニング記録 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["trainingdto.RecordTrainingRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["trainingdto.RecordTrainingResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trainings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** トレーニング取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 対象 TrainingID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["trainingdto.TrainingDTO"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        /** トレーニング記録更新 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 対象 TrainingID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description 更新用トレーニング記録 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["trainingdto.UpdateTrainingRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["trainingdto.UpdateTrainingResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /** トレーニング削除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 対象 TrainingID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ユーザー登録
         * @description 新規ユーザーを作成する(認証不要)
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description ユーザー登録情報 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["userdto.RegisterRequest"];
                };
            };
            responses: {
                /** @description ユーザー登録成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["userdto.RegisterResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ユーザー情報取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["userdto.UserDTO"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/profile-image/presigned-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** プロフィール画像のPresigned URL生成 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description プロフィール画像のPresigned URL生成情報 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["userdto.GenerateProfileImagePresignedURLRequest"];
                };
            };
            responses: {
                /** @description プロフィール画像のPresigned URL生成成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["userdto.GenerateProfileImagePresignedURLResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ユーザー取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 対象 UserID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["userdto.UserDTO"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** ユーザー削除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 対象 UserID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["httpx.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "authdto.AccessTokenResponse": {
            access_token?: string;
            access_token_expires_at?: string;
        };
        "authdto.LoginRequest": {
            email?: string;
            password?: string;
        };
        "httpx.ErrorDetail": {
            code?: string;
            data?: {
                [key: string]: unknown;
            };
            message?: string;
        };
        "httpx.ErrorResponse": {
            error?: components["schemas"]["httpx.ErrorDetail"];
        };
        "mealdto.ListMealsResponse": {
            meals?: components["schemas"]["mealdto.MealDTO"][];
            pagination?: components["schemas"]["shareddto.PaginationDTO"];
        };
        "mealdto.MealDTO": {
            calories?: number;
            carbohydrate_g?: string;
            created_at?: string;
            eaten_at?: string;
            fat_g?: string;
            id?: string;
            meal_type?: string;
            memo?: string;
            photos?: components["schemas"]["mealdto.PhotoDTO"][];
            protein_g?: string;
            updated_at?: string;
            user_id?: string;
        };
        "mealdto.MealPhotoInput": {
            display_order?: number;
            image_path?: string;
        };
        "mealdto.PhotoDTO": {
            display_order?: number;
            image_url?: string;
        };
        "mealdto.RecordMealRequest": {
            calories?: number;
            carbohydrate_g?: number;
            eaten_at?: string;
            fat_g?: number;
            meal_type?: string;
            memo?: string;
            photos?: components["schemas"]["mealdto.MealPhotoInput"][];
            protein_g?: number;
        };
        "mealdto.RecordMealResponse": {
            meal_id?: string;
        };
        "mealdto.UpdateMealRequest": {
            calories?: number;
            carbohydrate_g?: number;
            eaten_at?: string;
            fat_g?: number;
            meal_type?: string;
            memo?: string;
            photos?: components["schemas"]["mealdto.MealPhotoInput"][];
            protein_g?: number;
        };
        "mealdto.UpdateMealResponse": {
            meal_id?: string;
        };
        "shareddto.PaginationDTO": {
            current_page?: number;
            items_per_page?: number;
            total_items?: number;
            total_pages?: number;
        };
        "trainingdto.ExerciseDTO": {
            created_at?: string;
            id?: string;
            name?: string;
            updated_at?: string;
            user_id?: string;
        };
        "trainingdto.ListExercisesResponse": {
            exercises?: components["schemas"]["trainingdto.ExerciseDTO"][];
            pagination?: components["schemas"]["shareddto.PaginationDTO"];
        };
        "trainingdto.ListRoutinesResponse": {
            pagination?: components["schemas"]["shareddto.PaginationDTO"];
            routines?: components["schemas"]["trainingdto.RoutineDTO"][];
        };
        "trainingdto.ListTrainingsResponse": {
            pagination?: components["schemas"]["shareddto.PaginationDTO"];
            trainings?: components["schemas"]["trainingdto.TrainingDTO"][];
        };
        "trainingdto.RecordTrainingExerciseRequest": {
            display_order?: number;
            exercise_id?: string;
            memo?: string;
            rest_seconds?: number;
            sets?: components["schemas"]["trainingdto.RecordTrainingSetRequest"][];
        };
        "trainingdto.RecordTrainingRequest": {
            ended_at?: string;
            exercises?: components["schemas"]["trainingdto.RecordTrainingExerciseRequest"][];
            memo?: string;
            started_at?: string;
        };
        "trainingdto.RecordTrainingResponse": {
            training_id?: string;
        };
        "trainingdto.RecordTrainingSetRequest": {
            memo?: string;
            reps?: number;
            rest_seconds?: number;
            set_number?: number;
            weight_kg?: string;
        };
        "trainingdto.RoutineDTO": {
            created_at?: string;
            id?: string;
            name?: string;
            routine_exercises?: components["schemas"]["trainingdto.RoutineExerciseDTO"][];
            updated_at?: string;
            user_id?: string;
        };
        "trainingdto.RoutineExerciseDTO": {
            display_order?: number;
            exercise_id?: string;
            exercise_name?: string;
            id?: string;
        };
        "trainingdto.TrainingDTO": {
            created_at?: string;
            ended_at?: string;
            exercises?: components["schemas"]["trainingdto.TrainingExerciseDTO"][];
            id?: string;
            memo?: string;
            started_at?: string;
            updated_at?: string;
            user_id?: string;
        };
        "trainingdto.TrainingExerciseDTO": {
            display_order?: number;
            exercise_id?: string;
            id?: string;
            memo?: string;
            rest_seconds?: number;
            sets?: components["schemas"]["trainingdto.TrainingSetDTO"][];
        };
        "trainingdto.TrainingSetDTO": {
            id?: string;
            memo?: string;
            reps?: number;
            rest_seconds?: number;
            set_number?: number;
            /** @description weightは精度のためstringとして持つ */
            weight_kg?: string;
        };
        "trainingdto.UpdateTrainingRequest": {
            ended_at?: string;
            exercises?: components["schemas"]["trainingdto.RecordTrainingExerciseRequest"][];
            memo?: string;
            started_at?: string;
        };
        "trainingdto.UpdateTrainingResponse": {
            training_id?: string;
        };
        "trainingdto.UpsertExerciseRequest": {
            name?: string;
        };
        "trainingdto.UpsertExerciseResponse": {
            id?: string;
        };
        "trainingdto.UpsertRoutineExerciseRequest": {
            display_order?: number;
            exercise_id?: string;
        };
        "trainingdto.UpsertRoutineRequest": {
            exercises?: components["schemas"]["trainingdto.UpsertRoutineExerciseRequest"][];
            name?: string;
        };
        "trainingdto.UpsertRoutineResponse": {
            id?: string;
        };
        "userdto.GenerateProfileImagePresignedURLRequest": {
            content_type?: string;
        };
        "userdto.GenerateProfileImagePresignedURLResponse": {
            path?: string;
            url?: string;
        };
        "userdto.RegisterRequest": {
            birthday?: string;
            email?: string;
            name?: string;
            password?: string;
        };
        "userdto.RegisterResponse": {
            user_id?: string;
        };
        "userdto.UserDTO": {
            birthday?: string;
            created_at?: string;
            email?: string;
            id?: string;
            name?: string;
            profile_image_url?: string;
            updated_at?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
